=== vbmundhe/mulesoftdemo/day3-transformdemo/src/main/resources/schemas/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/emp" xmlns:tns="http://www.example.org/emp" elementFormDefault="qualified">
<complexType name="skilltype">
    	<sequence>
    		<element name="title" type="string"></element>
    		<element name="category" type="string"></element>
    		<element name="proficiency">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    					<maxInclusive value="4"></maxInclusive>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>

    <complexType name="employeetype">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="role" type="string"></element>
    		<element name="skills" type="tns:skilllisttype"></element>
    	</sequence>
    	<attribute name="empid" type="string"></attribute>
    </complexType>


    <complexType name="skilllisttype">
    	<sequence>
    		<element name="skill" type="tns:skilltype" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="employee" type="tns:employeetype"></element>
</schema>

=== vbmundhe/mulesoftdemo/day3-transformdemo/src/main/resources/examples/emp.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:employee empid="1001" xmlns:tns="http://www.example.org/emp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/emp emp.xsd ">
  <tns:name>Nilesh</tns:name>
  <tns:role>Associate Manager</tns:role>
  <tns:skills>
    <tns:skill>
      <tns:title>DevOps</tns:title>
      <tns:category>industry</tns:category>
      <tns:proficiency>3</tns:proficiency>
    </tns:skill>
    <tns:skill>
      <tns:title>Agile</tns:title>
      <tns:category>industry</tns:category>
      <tns:proficiency>4</tns:proficiency>
    </tns:skill>
    <tns:skill>
      <tns:title>Java</tns:title>
      <tns:category>technology</tns:category>
      <tns:proficiency>4</tns:proficiency>
    </tns:skill>
  </tns:skills>
</tns:employee>
